### ISSUE TITLE
Please use valid version numbers

### ISSUE THREAD

**Issue by atodorov** [farcepest/MySQLdb1#11]
According to python2.6/distutils/version.py: 

```
 63 class StrictVersion (Version):
 64 
 65     """Version numbering for anal retentives and software idealists.
 66     Implements the standard interface for version number classes as
 67     described above.  A version number consists of two or three
 68     dot-separated numeric components, with an optional "pre-release" tag
 69     on the end.  The pre-release tag consists of the letter 'a' or 'b'
 70     followed by a number.
```

According to this some of your earlier versions are not valid, namely: 
1.2.4c1 
1.2.3c1 
1.2.2c1 
1.2.1_p2 
1.2.1c8
1.2.1c7
1.2.1c6
1.2.1c5
1.2.1c4
1.2.1c3
1.2.1c2
1.2.1c1
1.0.1c1 
1.0.0c2 
0.9.2c3 
0.9.2c2
0.9.2c1
0.9.1c2 
0.9.1c1

This has a side effect when comparing versions with the standard python utils (and possibly when trying to update older packages) that the X.Y.Zc1 is considered newer than X.Y.Z

Please have this in mind for your next releases.

**Comment by farcepest** [comment]
I'm pretty sure it's in compliance with [PEP-386](http://www.python.org/dev/peps/pep-0386/), excepting 1.2.1_p2. But cut me some slack there as 1.2.3 was released a couple years ago.

**Comment by farcepest** [comment]
The only version not in compliance with PEP-386 was released in 2006, three years before PEP-386 was created....
