### ISSUE TITLE
ImportError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by ghost** [farcepest/MySQLdb1#120]
I got the error in the header when running
pip install MySQL-python

The reason was that there is no module names 'ConfigParser'.
Correct name is in all small caps 'configparser'

You can manaully edit /var/folders/lf/myf7bjr57_jg7_5c4014bh640000gn/T/pip-build/MySQL-python/setup_posix.py.  Change ConfigParser to configparser and run pip again.

**Comment by farcepest** [comment]
No

**Comment by ghost** [comment]
No? Please clarify?

**Comment by farcepest** [comment]
https://docs.python.org/2.7/library/configparser.html#module-ConfigParser

Changing that reference does not magically make everything work in Python 3.

**Comment by ghost** [comment]
ok, point taken. I was able to install without error... but whether i can use it without errors is yet to be proven.

**Comment by methane** [comment]
@anthonycooray Try [mysqlclient](https://pypi.python.org/pypi/mysqlclient).  It's my fork of this project.
It supports Python 3 and newer MySQL and MariaDB.

@farcepest What do you feel about merging mysqlclient and MySQLdb1?

**Comment by farcepest** [comment]
@methane you want me to merge your fork?

My problem is, I don't have the time to do anything with MySQLdb, and in fact have not been a regular user for nearly three years, so someone else should become the official maintainer. It may be best to relocate this to some kind of project account within GitHub.

**Comment by methane** [comment]
@farcepest My problem is branding and PyPI package confusion.
For now, mysqlclient is fork of your project, uses different PyPI package name, but uses same
Python package name ("MySQLdb"). So mysqlclient and MySQL-python conflict each other.

So best option for me is: You admit me as a maintainer of MySQL-python, and add me
to PyPI package's owner role.

I'm afraid my poor English says something impolite. I respect your long work about MySQL-python.
If you don't want to approve me as maintaner of MySQL-python, I'll continue to use mysqlclient brand.
