### ISSUE TITLE
Which PyPI package is this? Mention the PyPI name in documentation

### ISSUE THREAD

**Issue by Flimm** [farcepest/MySQLdb1#139]
I'm not sure which PyPI package this is meant to be. Could the README.md contain a link to the correct PyPI package?

It would also be helpful if the sourceforge.net page also mentioned the PyPI package name.

**Comment by hugovk** [comment]
https://pypi.org/project/MySQL-python/ links here, and that name is the `name` in the setup*.py files.

**Comment by hugovk** [comment]
And see https://github.com/PyMySQL/mysqlclient-python / https://pypi.org/project/mysqlclient/ for a maintained fork.
