### ISSUE TITLE
install of MySQLdb1 fails on centos 7

### ISSUE THREAD

**Issue by ichibrosan** [farcepest/MySQLdb1#143]
root@ichibrosan MySQLdb1-master]# python setup.py install
sh: mysql_config: command not found
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    metadata, options = get_config()
  File "/root/MySQLdb1-master/setup_posix.py", line 43, in get_config
    libs = mysql_config("libs_r")
  File "/root/MySQLdb1-master/setup_posix.py", line 25, in mysql_config
    raise EnvironmentError("%s not found" % (mysql_config.path,))
EnvironmentError: mysql_config not found
[root@ichibrosan MySQLdb1-master]# 

I would really appreciate a clue where to go with this, I am going around in circles and getting dizzy.

**Comment by vishal-yadav** [comment]
First install mysql-client for your distribution which contains mysql_config. For CentOS 7, it will be mariadb-devel package.

**Comment by ichibrosan** [comment]
Thank you most kindly. Stress level reduced. :-)
