### ISSUE TITLE
wrong literal for list when query

### ISSUE THREAD

**Issue by lexdene** [farcepest/MySQLdb1#15]
this is the test code:

```
import MySQLdb

conn = MySQLdb.connect(user='xxx',passwd='xxx',db = 'xxx')

cursor = conn.cursor()

n = cursor.execute(
    'select * from xxx where `content` in %(content)s',
    { 'content': ('aa','bb','cc') }
)
print cursor._last_executed
```

I hope it print:

```
select * from xxx where `content` in ('aa', 'bb', 'cc')
```

but actually it print:

```
select * from xxx where `content` in ("'aa'", "'bb'", "'cc'")
```

and because of this , the query fetch nothing.

Is this a bug of MySQLdb ?

my system:
- Ubuntu 12.04.2 LTS
- Python 2.7.3
- MySQLdb 1.2.3

**Comment by maixiaohai** [comment]
沙发

**Comment by farcepest** [comment]
Substituting a variable length list of parameters is problematic in DB-API. Try this instead:

```
content = ('aa','bb','cc')
query = 'select * from xxx where `content` in (%s)' % (','.join(['%s']*len(content))
cursor.execute(query, content)
```

The above is slightly ugly but should work with all database adapters. Maybe a helper function would be useful?

Note that you shouldn't depend on the return value of cursor.execute for the number of rows; use cursor.rowcount instead.

**Comment by lexdene** [comment]
The code you provided works .

Thank you .
