### ISSUE TITLE
Speed up installs from PyPI Using Explicit Url Controls

### ISSUE THREAD

**Issue by dstufft** [farcepest/MySQLdb1#16]
Hey there!

Your package on PyPI has several external urls that must be scraped everytime pip/easy_install attempts to install your package. It would be great if you could use the new PyPI feature to control the urls so that scraping multiple external sites is no longer required.

As you can see from http://pypi-externals.caremad.io/MySQL-python/ None of the external scrape targets offer any installation targets so they are pure waste.

You can see how to do this at http://pypi-externals.caremad.io/help/what/

**Comment by farcepest** [comment]
I think this is fixed. Comment?

**Comment by dstufft** [comment]
Yup! Perfect thanks.
