### ISSUE TITLE
Is MySQLdb support Prepared Statements ?

### ISSUE THREAD

**Issue by lexdene** [farcepest/MySQLdb1#17]
A prepared statement is used to execute the same statement repeatedly with high efficiency and safety .
The prepared statement execution consists of two stages: prepare and execute. At the prepare stage a statement template is send to the database server. The server performs a syntax check and initializes server internal resources for later use.

Is MySQLdb support Prepared Statements ?

**Comment by farcepest** [comment]
Prior to MySQL-5.1, prepared statements did not make use of MySQL query cache, so they weren't worth adding. Since this is changed, it might be worth another look.

**Comment by farcepest** [comment]
Will look again for 1.3

**Comment by lexdene** [comment]
That's good !
