### ISSUE TITLE
MySQL-python 1.2.2 download link broken on PyPI

### ISSUE THREAD

**Issue by qris** [farcepest/MySQLdb1#7]
http://pypi.python.org/pypi/MySQL-python/1.2.2 refers to http://internap.dl.sourceforge.net/sourceforge/mysql-python/MySQL-python-1.2.2.tar.gz, which doesn't resolve.

http://download.sourceforge.net/sourceforge/mysql-python/MySQL-python-1.2.2.tar.gz would probably work.

Someone reported this to sourceforge/PyPI a year ago, but they closed the issue because they said it's up to the package maintainer to fix it:

http://sourceforge.net/tracker/?func=detail&aid=3107645&group_id=66150&atid=513503

**Comment by farcepest** [comment]
Honestly, there is no good reason to be using 1.2.2. It's five and a half years old, and hasn't been shown on PyPI for a very long time. However I have fixed the problem by removing the download link.

If for some crazy-ass reason you insist on having 1.2.2, you can check it out from github with:

git clone git@github.com:farcepest/MySQLdb1.git@MySQLdb-1.2.2

or download the zipwad from https://github.com/farcepest/MySQLdb1/zipball/MySQLdb-1.2.2

But I very strongly recommend you use 1.2.4 (still beta but the full release is nearly ready, it just needs documentation cleanups). If you have a legitimate reason that requires you to use 1.2.2, I'd like to hear it.

**Comment by qris** [comment]
I cannot use 1.2.4 because of issue #6. I thought Windows was stuck on 1.2.2, but there is a 1.2.3 binary egg now, so I can use that.
