### ISSUE TITLE
mysql and Python: does not allow two timestamp columns

### ISSUE THREAD

**Issue by jakobgt** [farcepest/MySQLdb1#76]
I'm having issues with Python, MySQL and creating a table with two timestamp columns.

Executing the following SQL through Python and using MySQLDB:

CREATE TABLE test_db.test_with_two_datetime_columns (
    `first_datetime_field` TIMESTAMP(6) NOT NULL DEFAULT 0,
    `second_datetime_field` TIMESTAMP(6) NOT NULL DEFAULT 0
) ENGINE=InnoDB 
I get the error (1067, Invalid default value for 'first_datetime_field'), whereas I can easily fire of the following equal command in the MySQL CLI:

$ mysql -h localhost

> CREATE TABLE test_db.test_with_two_datetime_columns (
>       `first_datetime_field` TIMESTAMP(6) NOT NULL DEFAULT 0,
>       `second_datetime_field` TIMESTAMP(6) NOT NULL DEFAULT 0
>   ) ENGINE=InnoDB;
> Query OK, 0 rows affected (0.01 sec)
> Similarly through Sequel Pro the above command executes fine.

So I'm guessing the problem is with MySQLDB (aka. MySQL-Python), but that seems very weird, IMHO.

Running this query instead is ok:

CREATE TABLE test_db.test_with_two_datetime_columns (
    `first_datetime_field` TIMESTAMP(6) NULL DEFAULT NULL,
    `second_datetime_field` TIMESTAMP(6) NULL DEFAULT NULL
) ENGINE=InnoDB""")

I'm using MySQL 5.6.17, MySQL-Python 1.2.5 and Python 2.7.

The Stackoverflow thread: http://stackoverflow.com/questions/24511573/mysql-and-python-does-not-allow-two-timestamp-columns/24512549

**Comment by methane** [comment]
What is result of this query?

```
SELECT @@session.sql_mode;
```

**Comment by jakobgt** [comment]
Ahh nice trick. The output:

STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

I see that NO_ZERO_IN_DATE and NO_ZERO_DATE are present, which is because sql_mode traditional had been set in a wrapper I use for MySQLDB, that I was unaware of. Thanks a lot for the nice debug query, and sorry to bother you.
