### ISSUE TITLE
Tag last commit as 1.2.4

### ISSUE THREAD

**Issue by glarrain** [farcepest/MySQLdb1#9]
The commit ad119309fc561ae28bab6493ca4bd20b36319cf2 (2013-1-1) should be tagged in the repo as 1.2.4

**Comment by farcepest** [comment]
I tagged it locally, but the tool I use (PyCharm) doesn't have an option to push tags, so it was overlooked. Will push it out shortly.

**Comment by glarrain** [comment]
Thank you. I use PyCharm too, and like it a lot, but I find its SCM integration weird and not friendly.

**Comment by farcepest** [comment]
Actually, I think PyCharm's integration with git is generally great, but not being about to push tags is a weird omission. At any rate, that tag's pushed out now.
